services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      # 左側がコンテナ内の変数名、右側が .env から読み込む変数名
     - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
     - TZ=Asia/Tokyo  # ログのためにUTCからJSTにする
     # キャッシュする画像数を0にする（メモリに保持しない）
     - VIPS_CACHE_MAX=0
     # キャッシュメモリサイズを制限する（10MB程度に制限）
     - VIPS_CACHE_MAX_MEM=10000000
     # GCを積極的に動かすための設定
     - RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=1.2
     - RUBY_GC_MALLOC_LIMIT=4000000
     - RUBY_GC_MALLOC_LIMIT_MAX=16000000
    deploy:
      resources:
        limits:
          memory: 550M
  db:
    image: mariadb:10.11
    restart: always
    command: --innodb-buffer-pool-size=64M --innodb-log-buffer-size=8M --max-connections=20 --innodb-temp-data-file-path=ibtmp1:12M:autoextend:max:32M
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      TZ: Asia/Tokyo
    deploy:
      resources:
        limits:
          memory: 128M
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data: