services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      # 左側がコンテナ内の変数名、右側が .env から読み込む変数名
     - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}